petroleum/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'petroleum'

urlpatterns = [
    path('data', views.petrol, name = 'petroleums'),
    path('', views.result, name = 'result'),

    ]

yipl_intern_petroleum_report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petroleum.urls', namespace='petroleum'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petroleum/models.py
from django.db import models

# Create your models here.
class Petroleum(models.Model):
    year = models.IntegerField()
    petroleum = models.CharField(max_length=30)
    sale = models.IntegerField()

    def __str__(self):
        return self.petroleum

petroleum/views.py
from django.shortcuts import render
import requests
from .models import Petroleum
import json

# Create your views here.
def petrol(request):
    response = requests.get('https://raw.githubusercontent.com/younginnovations/internship-challenges/master/programming/petroleum-report/data.json')
    data = json.loads(response.content.decode('utf-8'))
    datas = Petroleum.objects.all()
    for d in data:
        year = (d['year'])
        sale = d['sale']
        petroleum = d['petroleum_product']
        obj, created = Petroleum.objects.get_or_create(year=year, petroleum=petroleum, sale=sale)

    context = {
        'data': data,
        'objects': datas

    }
    return render(request, 'index.html', context)


def result(request):
    petroleum = Petroleum.objects.values_list('petroleum',flat=True).distinct()
    resultdata = []
    dataset = Petroleum.objects.all().order_by('-year')
    for j in range(len(petroleum)):
        count=0
        c =0
        first_loop=True
        total_sale=0
        max=0
        min=0
        for i,datas in enumerate(dataset):
            if(petroleum[j]==datas.petroleum):
                if(first_loop):
                    first = int(datas.year)
                last = int(datas.year)
                if (last == first - 5):
                    resultdata.append([petroleum[j], str(last+1) + "-" + str(last + 5),min, max, total_sale/(1 if count==0 else count)])
                    total_sale = 0
                    count=0
                    first = last
                    max = 0
                    min = datas.sale
                count = count + 1  if datas.sale != 0 else count
                total_sale = total_sale + datas.sale
                max = max if max>datas.sale else datas.sale
                min = datas.sale if min == 0 else (min if min < datas.sale else datas.sale)
                first_loop= False
        count = 1 if count == 0 else count
        resultdata.append([petroleum[j], str(last) + "-" + str(last+4),min, max,total_sale/ count])
    data = {
        'resultdata': resultdata
    }
    return render(request, 'result.html', data)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Data||Young Innovation</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <table class="table">
    <thead>
      <tr>
        <th>Product</th>
        <th>Year</th>
        <th>Sale</th>
      </tr>
    </thead>
    <tbody>
    {% for d in data %}
        <tr>
            <td>{{d.petroleum_product}}</td>
            <td>{{d.year}}</td>
            <td>{{d.sale}}</td>
        </tr>
     {% endfor %}
    </tbody>
  </table>
</div>

</body>
</html>
</body>
</html>

templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Output-Intern of Young Innovations</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <br>
  <center><h5> The given data are in api are inside this <a href="{% url 'petroleum:petroleums' %}" >link</a></h5></center>
  <center><h6>Young Innovation Intern Apply</h6></center>
  <br><br>
  <table class="table">
    <thead>
      <tr>
        <th>Product</th>
        <th>Year</th>
        <th>Min</th>
        <th>Max</th>
        <th>Avg</th>
      </tr>
    </thead>
    <tbody>
    {% for r in resultdata %}
      <tr>
        <td>{{r.0}}</td>
        <td>{{r.1}}</td>
        <td>{{r.2}}</td>
        <td>{{r.3}}</td>
        <td>{{r.4}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

</body>
</html>
</body>
</html>